### ISSUE TITLE
ansj插件在es5.2.2和5.4.0中使用有问题

### ISSUE THREAD

**Issue by Garry1205** [NLPchina/ansj_seg#531]
以前用过es1.6开发项目，中文分词插件就是使用ansj，那个版本完全没有问题。
最近要升级es版本，发现无论在es5.2.2还是在es5.4.0，ansj好像都有些问题。
5.2的问题是，自定义词库不生效，我把自定义词库删除，新建一个dic，里面只新建一个词，“中国人民大学'\t'ntu'\t'132”，然后分词的时候仍然会被分成“中国”，“人民”，“大学”。自定义词典需要特别的配置吗。
5.4自定义词库是生效的，但是一些特别高频的词，就会被干掉了，比如我对“学习”分词，分词结果为空。不干掉高频词是需要额外配置吗。
无论是在es5.2.2还是在es5.4.0，我的配置文件都是一样的，如下：

ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false; #是否保留真实词语,建议保留false
  #用户自定词典配置
  dic: file:///usr/local/elasticsearch-5.4.0/plugins/elasticsearch-analysis-ansj/config/default.dic
 #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
 #过滤词典配置
  stop: file:///usr/local/elasticsearch-5.4.0/plugins/elasticsearch-analysis-ansj/config/stop.dic #都支持

配置文件里非注释内容只有这些，而且我确定路径没有写错。

验证url是：
es5.2.2:
http://10.97.14.141:9200/test/_analyze?analyzer=index_ansj&text=中国人民大学
结果：
{"tokens":[{"token":"中国","start_offset":0,"end_offset":2,"type":"ns","position":1},{"token":"人民","start_offset":2,"end_offset":4,"type":"n","position":4},{"token":"大学","start_offset":4,"end_offset":6,"type":"n","position":8}]}

es5.4.0
http://10.97.14.141:9200/test/_analyze?analyzer=index_ansj&text=学习
结果：
{"tokens":[]}

请问这样的问题可能的原因是什么？

**Comment by shi-yuan** [comment]
我试了一下，没问题的，升级下插件试试。。。

**Comment by shi-yuan** [comment]
dic：
```
中国人民大学	a	144099
```

ansj.cfg.yml：
```yml
# 全局变量配置方式一
ansj:
  #默认参数配置
  isNameRecognition: true #开启姓名识别
  isNumRecognition: true #开启数字识别
  isQuantifierRecognition: true #是否数字和量词合并
  isRealName: false #是否保留真实词语,建议保留false

  #用户自定词典配置
  dic: D:/elasticsearch/elasticsearch-5.5.0/plugins/elasticsearch-ansj-plugin/config/dic #也可以写成 file://default.dic , 如果未配置dic,则此词典默认加载
```

验证：http://localhost:9200/_analyze?analyzer=index_ansj&text=%E4%B8%AD%E5%9B%BD%E4%BA%BA%E6%B0%91%E5%A4%A7%E5%AD%A6
```json
{
    tokens: [
        {
            token: "中国人民大学",
            start_offset: 0,
            end_offset: 6,
            type: "a",
            position: 0
        }
    ]
}
```
